### ISSUE TITLE
Transitions from light to dark mode don't work

### ISSUE THREAD

**Issue by kleinesNugget** [pacocoursey/next-themes#181]
I'm running into an issue where the colour transitions don't work when changing from light to dark mode. They do work when changing from dark to light mode though.
I'm using Tailwind CSS, the Next.JS app dir and the following props for the ThemeProvider:
- attribute="class"
- defaultTheme="system"
- enableSystem

I have tried adding "disableTransitionOnChange=false" but that didn't change anything. Setting it to true did disable all transitions, on every theme, as expected.
I've also tried writing my own little script to add and remove the "dark" class, which worked completely fine, and there were no issues with transitions. My script obviously didn't have the comforts of next-themes though, hence I'm trying to get this resolved.

If there's any information I didn't mention, that is required to solve this issue, feel free to ask :)
Thanks in advance

**Comment by lundjrl** [comment]
@kleinesNugget Not sure if this is still an issue for you but I used [this fork](https://github.com/WITS/next-themes) and dark mode works for the app dir in Next.js 13.4.0 

The `ChangeThemeButton.tsx` component is used within the <Header /> component in the root layout.

Implementation:
<img width="741" alt="Petrify 2023-05-25 at 1 01 18 PM" src="https://github.com/pacocoursey/next-themes/assets/35306013/46165e94-8ab9-4c78-a03a-1bde6d27f516">

<img width="901" alt="Petrify 2023-05-25 at 1 03 11 PM" src="https://github.com/pacocoursey/next-themes/assets/35306013/be4875d8-ea2f-4ead-be86-e2a6284b1af7">

**Comment by kleinesNugget** [comment]
After testing the fork, I've not noticed any difference. But then I tried something which worked. I've put some styling from the body into a div wrapping the main content instead and I've specified colours for the light mode without the "dark:" tag.
That seems to have fixed my issue, but now I'm running into the issue that transitions don't properly work on chrome browsers because of some inheriting issue (https://stackoverflow.com/questions/30019451/what-is-causing-this-css-transition-delay-specifically-with-colours-in-chrome) But I guess that's "easily" fixed by adding the transition property to everything I want to change.

**Comment by lundjrl** [comment]
I might be newish to Tailwind but don't you normally need to add the transition property for animations? And doesn't the wrapping div cause hydration errors?

Also, how does this work with `next start` vs `next dev`? A prod build seems flawless on my end.

**Comment by kleinesNugget** [comment]
> I might be newish to Tailwind but don't you normally need to add the transition property for animations? And doesn't the wrapping div cause hydration errors?

If you don't add a transition property, it won't have a transition. For animations, you don't need a transition property, not sure if I understood you right here.
If I put the "ThemeProvider" around the body tags it causes one, if I put it within the body tag and within the theme provider another div tag that wraps header, main and footer, it works flawlessly.

> Also, how does this work with `next start` vs `next dev`? A prod build seems flawless on my end.
For both it's the same issue. The transition issues when using inheriting transitions (for example: `body * { @apply transition-colors; }`) apparently only happens on webkit-browsers as firefox does it completely fine.
My previous main issue was also on prod & dev, but that was already fixed by specifying the none dark mode colours as well on the wrapping div.

**Comment by leviptz** [comment]
I have the same Issue. None of the answers helped to far. There is always a Error:
"Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <script> in <html>."

**Comment by lundjrl** [comment]
@leviptz I think that's agnostic of the fork I provided. What Next.js and fork version are you on?

**Comment by leviptz** [comment]
Just forked the fork you provided and tried to npm install it via leviptz/next-themes
I got this Error:

105 error code 127
106 error git dep preparation failed
107 error command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/leviptz/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
108 error > @wits/next-themes@0.2.16 prepublish
108 error > yarn build
109 error npm WARN using --force Recommended protections disabled.
109 error npm WARN ERESOLVE overriding peer dependency
109 error npm WARN While resolving: next@12.1.0
109 error npm WARN Found: react@17.0.1
109 error npm WARN node_modules/react
109 error npm WARN   dev react@"^17.0.1" from the root project
109 error npm WARN   4 more (@testing-library/react, react-dom, styled-jsx, use-subscription)
109 error npm WARN 
109 error npm WARN Could not resolve dependency:
109 error npm WARN peer react@"^17.0.2 || ^18.0.0-0" from next@12.1.0
109 error npm WARN node_modules/next
109 error npm WARN   peer next@"*" from the root project
109 error npm WARN   1 more (@types/next)
109 error npm WARN 
109 error npm WARN Conflicting peer dependency: react@18.2.0
109 error npm WARN node_modules/react
109 error npm WARN   peer react@"^17.0.2 || ^18.0.0-0" from next@12.1.0
109 error npm WARN   node_modules/next
109 error npm WARN     peer next@"*" from the root project
109 error npm WARN     1 more (@types/next)
109 error npm WARN ERESOLVE overriding peer dependency
109 error npm WARN While resolving: next@12.1.0
109 error npm WARN Found: react-dom@17.0.1
109 error npm WARN node_modules/react-dom
109 error npm WARN   dev react-dom@"^17.0.1" from the root project
109 error npm WARN   1 more (@testing-library/react)
109 error npm WARN 
109 error npm WARN Could not resolve dependency:
109 error npm WARN peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.1.0
109 error npm WARN node_modules/next
109 error npm WARN   peer next@"*" from the root project
109 error npm WARN   1 more (@types/next)
109 error npm WARN 
109 error npm WARN Conflicting peer dependency: react-dom@18.2.0
109 error npm WARN node_modules/react-dom
109 error npm WARN   peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.1.0
109 error npm WARN   node_modules/next
109 error npm WARN     peer next@"*" from the root project
109 error npm WARN     1 more (@types/next)
109 error npm WARN deprecated @types/next@9.0.0: This is a stub types definition. next provides its own type definitions, so you do not need this installed.
109 error npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
109 error npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
109 error npm WARN deprecated har-validator@5.1.5: this library is no longer supported
109 error npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
109 error npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
109 error npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
109 error npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
109 error npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
109 error npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
109 error npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
109 error npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
109 error npm WARN deprecated core-js-pure@3.9.1: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
109 error sh: yarn: command not found
109 error npm ERR! code 127
109 error npm ERR! path /Users/leviptz/.npm/_cacache/tmp/git-cloneeAbRr7
109 error npm ERR! command failed
109 error npm ERR! command sh -c yarn build
109 error
109 error npm ERR! A complete log of this run can be found in:
109 error npm ERR!     /Users/leviptz/.npm/_logs/2023-06-02T12_49_05_078Z-debug-0.log
110 verbose exit 127
111 timing npm Completed in 10956ms
112 verbose unfinished npm timer reify 1685710142118
113 verbose unfinished npm timer reify:unpack 1685710144185
114 verbose unfinished npm timer reifyNode:node_modules/next-themes 1685710144187
115 verbose code 127
116 error A complete log of this run can be found in:
116 error     /Users/leviptz/.npm/_logs/2023-06-02T12_49_02_067Z-debug-0.log

**Comment by salmidiv** [comment]
this solution work for me 

```
"use client";
import { useTheme } from "next-themes";
import { BiSun, BiMoon } from "react-icons/bi";
import Loader from "../utils/loader";
import { useEffect, useState } from "react";
const ThemeSwitcher = () => {
  const { systemTheme, theme, setTheme } = useTheme();
  const currentTheme = theme === "system" ? systemTheme : theme;
  const [sthem, setStheme] = useState(null);

  useEffect(() => {
    setStheme(currentTheme);
  }, [sthem]);

  function changeTheme(selectedthem) {
    setStheme(selectedthem);
    setTheme(selectedthem);
  }
  return (
    <div
      className="nui-focus relative flex h-9 w-9 shrink-0 cursor-pointer items-center justify-center overflow-hidden rounded-md border border-muted-300 bg-white transition-all duration-100 focus-visible:outline-2 dark:border-muted-700 dark:bg-muted-800 dark:ring-offset-muted-900"
      onClick={() => changeTheme(sthem === "dark" ? "light" : "dark")}
    >
      {!sthem ? (
        <Loader />
      ) : sthem === "dark" ? (
        <BiSun className="h-5 w-5 text-yellow-400" />
      ) : (
        <BiMoon className="h-5 w-5" />
      )}
    </div>
  );
};
export default ThemeSwitcher;
```
