### ISSUE TITLE
can we use more than one ThemeProviders in one app?

### ISSUE THREAD

**Issue by thoughtlessmind** [pacocoursey/next-themes#184]
Hello,
First, I'll explain my use Case:

I'm making an app in which there are two color modes
1. Dark/Ligh/System Theme: in this user can select the theme
2. Color palette selection: in this user can select a color palette theme. It can set values like `teal`, `orange`, `blue`, etc. 

and then based on those two values, the final theme would be calculated/rendered. We can have different storage keys for both providers.

Currently, it can only have one theme.
Thanks

**Comment by abcdefghijorngarbosaxyz** [comment]
You would need to create your own context provider for that.

**Comment by pacocoursey** [comment]
This currently is not supported, particularly because `ThemeProvider` injects a script that is expected to be as close as possible to the opening `<body>` tag.

Could you make your theme values be like `dark:teal`, `light:blue`, etc? I know it makes a lot more themes, but at least it flat.

You could still style it using some creative CSS selectors, like:

```css
[data-theme^="light"] {
  ...light mode vars...
}

[data-theme~=":blue"] {
  ...blue mode vars...
}
```

**Comment by thoughtlessmind** [comment]
thanks, @pacocoursey 
actually, I proceeded with the same method.. :) 
thanks for the suggestion
