### ISSUE TITLE
ThemeProvider returns multiple types

### ISSUE THREAD

**Issue by javi95z** [pacocoursey/next-themes#279]
```
Type error: 'ThemeProvider' cannot be used as a JSX component. 
Its return type 'string | number | boolean | Iterable<ReactNode> | Element' is not a valid JSX element.
```

**Comment by vshakun** [comment]
Hello!

I have the same issue using 
```json
{
  "next-themes": "^0.3.0",
  "react": "^18.2.0", 
  "vite": "^5.2.8"
}
```

Downgrading `next-themes` to `^0.2.1` fixes the issue.

**Comment by flixlix** [comment]
Hey, I assume the issue is currently originating from here:
https://github.com/pacocoursey/next-themes/blob/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8/next-themes/src/index.tsx#L15

The type react node can be more things than just a JSX Element, so that is probably the issue (see https://reactnative.dev/docs/react-node).

I'll try to submit a PR to fix this issue

**Comment by particle4dev** [comment]
I'm still encountering this error, any updates?

**Comment by thedaviddias** [comment]
Same here.

**Comment by none23** [comment]
To fix the issue you need to upgrade `typescript` to v5.1+

**Comment by evsasse** [comment]
> To fix the issue you need to upgrade `typescript` to v5.1+

Using typescript `5.5.3` and still seeing this issue...

**Comment by none23** [comment]
Here's a minimal demo:
[Codesandbox](https://codesandbox.io/p/devbox/sad-borg-6h29ln)
Downgrade `typescript` to `"5.0.4"` to see this error
