### ISSUE TITLE
[Bug]: Hydration failed

### ISSUE THREAD

**Issue by bannednull** [pacocoursey/next-themes#317]
### What happened?

in recent version next js 15 not working

![image](https://github.com/user-attachments/assets/a9ba02c9-9681-4901-9d26-11c4c198d2ae)

### Version

0.3.0

**Comment by kareem717** [comment]
Hey bro, 

You need to make sure that the next-theme provider is mounted before returning it, like this: 

```
"use client";

import { ThemeProvider as NextThemesProvider } from "next-themes";
import { type ThemeProviderProps } from "next-themes/dist/types";
import { useEffect, useState } from "react";

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  const [isMounted, setIsMounted] = useState<boolean>(false);

  useEffect(() => {
    setIsMounted(true);
  });

  if (!isMounted) {
    return null;
  }

  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}
```

I also found this library that seems to solve the problem but to be honest I have not tried it: https://www.reddit.com/r/nextjs/comments/1dy0enr/new_theming_library_specifically_for_next_with_no/

**Comment by maxwiseman** [comment]
Isn't this intended behavior? I haven't gotten this error before the Next 15 release, but the readme says to add the `suppressHydrationWarning` prop to your `<html>` tag, which fixes it for me.

https://github.com/pacocoursey/next-themes/blob/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8/next-themes/README.md?plain=1#L95C1-L96C1

**Comment by bannednull** [comment]
@kareem717 Your solution is valid but it does not work to make ssr

**Comment by kareem717** [comment]
> @kareem717 Your solution is valid but it does not work to make ssr

I mean... obviously.

**Comment by maxwiseman** [comment]
> > @kareem717 Your solution is valid but it does not work to make ssr
> 
> I mean... obviously - the whole provider is a client component either way, it's built that way. In the README it says "Note that ThemeProvider is a client component, not a server component."
> 
> Try the library I tagged - I think it might solve the issue if you want it to be SSR

First of all, NextJS pre-renders client components on the server [(source)](https://nextjs.org/docs/app/building-your-application/rendering/client-components#:~:text=prerendered%20on%20the%20server). So by returning `null` on the initial render, you're effectively opting out of this pre-rendering. Secondly, since the provider wraps your entire app, it will need to be rendered in order for Next to SSR or SSG any given route. Next does not run `useEffect` or `useState` when pre-rendering client components, so this will just return `null`, overriding the entire route's server side render. You can prove this by simply disabling Javascript in your browser's devtools and loading a SSR or SSG page. You'll see a while screen. If you simply suppress the hydration warning, you'll see all your page content. By doing this, you are opting out of SSR and SSG for your entire app.

The library you linked would solve the problem for SSR (and would actually work better for SSR), but because it uses cookies to handle theme data, it opts out of SSG, which for many is a dealbreaker. There is a [prop to disable it](https://www.reddit.com/r/nextjs/comments/1dy0enr/comment/ld3tpul) for a route (which would enable SSG), but this isn't a very elegant solution.

This hydration error is fairly insignificant. React is able to sort everything out on its own, and we expect the `className` to be different on the client render because it will have access to the stored theme in `localStorage`, which will change the CSS class it applies. This error can and should just be ignored like it was prior to NextJS 15.

**Comment by kareem717** [comment]
> > > @kareem717 Your solution is valid but it does not work to make ssr
> 
> > 
> 
> > I mean... obviously - the whole provider is a client component either way, it's built that way. In the README it says "Note that ThemeProvider is a client component, not a server component."
> 
> > 
> 
> > Try the library I tagged - I think it might solve the issue if you want it to be SSR
> 
> 
> 
> First of all, NextJS pre-renders client components on the server [(source)](https://nextjs.org/docs/app/building-your-application/rendering/client-components#:~:text=prerendered%20on%20the%20server). So by returning `null` on the initial render, you're effectively opting out of this pre-rendering. Secondly, since the provider wraps your entire app, it will need to be rendered in order for Next to SSR or SSG any given route. Next does not run `useEffect` or `useState` when pre-rendering client components, so this will just return `null`, overriding the entire route's server side render. You can prove this by simply disabling Javascript in your browser's devtools and loading a SSR or SSG page. You'll see a while screen. If you simply suppress the hydration warning, you'll see all your page content. By doing this, you are opting out of SSR and SSG for your entire app.
> 
> 
> 
> The library you linked would solve the problem for SSR (and would actually work better for SSR), but because it uses cookies to handle theme data, it opts out of SSG, which for many is a dealbreaker. There is a [prop to disable it](https://www.reddit.com/r/nextjs/comments/1dy0enr/comment/ld3tpul) for a route (which would enable SSG), but this isn't a very elegant solution.
> 
> 
> 
> This hydration error is fairly insignificant. React is able to sort everything out on its own, and we expect the `className` to be different on the client render because it will have access to the stored theme in `localStorage`, which will change the CSS class it applies. This error can and should just be ignored like it was prior to NextJS 15.
> 
> 

Aye fair enough. Thanks for the tip.

**Comment by gfargo** [comment]
@kareem717 & @maxwiseman, thoughts on the proposed solution [in this comment](https://github.com/pacocoursey/next-themes/issues/316#issuecomment-2442051385)? i.e. wrapping the `ThemeProvider` in a `<Suspense>`  💭

**Comment by maxwiseman** [comment]
> Thoughts on the proposed solution [in this comment](https://github.com/pacocoursey/next-themes/issues/316#issuecomment-2442051385)? i.e. wrapping the `ThemeProvider` in a `<Suspense>` 💭

@gfargo That doesn't solve it for me. Does the error come back after you reload the page? Hydration errors can go away when you edit a file with the dev server running, but they sometimes come back after reloading the page.

I could be wrong, but I don't think `Suspense` would have any affect on `ThemeProvider` since it isn't a server component (and therefor isn't async), doesn't use `lazy`, and it doesn't currently make use of React 19's `use` hook. Those are the only things `Suspense` will wait for according to the React [docs](https://react.dev/reference/react/Suspense#:~:text=Data%20fetching%20with,Promise%20with%20use). Adding style and class attributes to a DOM element isn't async, so there's nothing for `Suspense` to wait on. Plus all of that code runs in an effect (as seen below), which doesn't activate `Suspense` according to the [docs](https://react.dev/reference/react/Suspense#:~:text=Suspense%20does%20not%20detect%20when%20data%20is%20fetched%20inside%20an%20Effect%20or%20event%20handler.).
https://github.com/pacocoursey/next-themes/blob/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8/next-themes/src/index.tsx#L135-L138

**Comment by pacocoursey** [comment]
Please read the docs: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app

**Comment by LikeDreamwalker** [comment]
> > > @kareem717 Your solution is valid but it does not work to make ssr
> > 
> > 
> > I mean... obviously - the whole provider is a client component either way, it's built that way. In the README it says "Note that ThemeProvider is a client component, not a server component."
> > Try the library I tagged - I think it might solve the issue if you want it to be SSR
> 
> First of all, NextJS pre-renders client components on the server [(source)](https://nextjs.org/docs/app/building-your-application/rendering/client-components#:~:text=prerendered%20on%20the%20server). So by returning `null` on the initial render, you're effectively opting out of this pre-rendering. Secondly, since the provider wraps your entire app, it will need to be rendered in order for Next to SSR or SSG any given route. Next does not run `useEffect` or `useState` when pre-rendering client components, so this will just return `null`, overriding the entire route's server side render. You can prove this by simply disabling Javascript in your browser's devtools and loading a SSR or SSG page. You'll see a while screen. If you simply suppress the hydration warning, you'll see all your page content. By doing this, you are opting out of SSR and SSG for your entire app.
> 
> The library you linked would solve the problem for SSR (and would actually work better for SSR), but because it uses cookies to handle theme data, it opts out of SSG, which for many is a dealbreaker. There is a [prop to disable it](https://www.reddit.com/r/nextjs/comments/1dy0enr/comment/ld3tpul) for a route (which would enable SSG), but this isn't a very elegant solution.
> 
> This hydration error is fairly insignificant. React is able to sort everything out on its own, and we expect the `className` to be different on the client render because it will have access to the stored theme in `localStorage`, which will change the CSS class it applies. This error can and should just be ignored like it was prior to NextJS 15.

I have a question, if next-themes is a client component, so will this actually block the RSCs? I am not sure that if we use a client component to wrap some server and client components, they will all go client component, which is SSR as well.

**Comment by LikeDreamwalker** [comment]
> > > > @kareem717 Your solution is valid but it does not work to make ssr
> > > 
> > > 
> > > I mean... obviously - the whole provider is a client component either way, it's built that way. In the README it says "Note that ThemeProvider is a client component, not a server component."
> > > Try the library I tagged - I think it might solve the issue if you want it to be SSR
> > 
> > 
> > First of all, NextJS pre-renders client components on the server [(source)](https://nextjs.org/docs/app/building-your-application/rendering/client-components#:~:text=prerendered%20on%20the%20server). So by returning `null` on the initial render, you're effectively opting out of this pre-rendering. Secondly, since the provider wraps your entire app, it will need to be rendered in order for Next to SSR or SSG any given route. Next does not run `useEffect` or `useState` when pre-rendering client components, so this will just return `null`, overriding the entire route's server side render. You can prove this by simply disabling Javascript in your browser's devtools and loading a SSR or SSG page. You'll see a while screen. If you simply suppress the hydration warning, you'll see all your page content. By doing this, you are opting out of SSR and SSG for your entire app.
> > The library you linked would solve the problem for SSR (and would actually work better for SSR), but because it uses cookies to handle theme data, it opts out of SSG, which for many is a dealbreaker. There is a [prop to disable it](https://www.reddit.com/r/nextjs/comments/1dy0enr/comment/ld3tpul) for a route (which would enable SSG), but this isn't a very elegant solution.
> > This hydration error is fairly insignificant. React is able to sort everything out on its own, and we expect the `className` to be different on the client render because it will have access to the stored theme in `localStorage`, which will change the CSS class it applies. This error can and should just be ignored like it was prior to NextJS 15.
> 
> I have a question, if next-themes is a client component, so will this actually block the RSCs? I am not sure that if we use a client component to wrap some server and client components, they will all go client component, which is SSR as well.

Got it: https://github.com/vercel/next.js/discussions/42301#discussioncomment-11600831

**Comment by victorteokw** [comment]
Use this to prevent hydration errors: https://github.com/victorteokw/next-safe-themes
