### ISSUE TITLE
data-theme & class at the same time?

### ISSUE THREAD

**Issue by genemators** [pacocoursey/next-themes#32]
I'd like to use attribute class and data-theme. How can I realise that?

In my case, I'm trying to combine my own css files with tailwind css. However, when I put attribute to class, none of my css aren't working, whilst tailwind itself doesn't on data-theme!

**Comment by pacocoursey** [comment]
I'm not why you would need both in this case. You can use Tailwind dark mode by simply specifying `attribute="class"`, and then in your regular CSS files you can use the `.dark` and `:root` selectors Does that work for you?

**Comment by genemators** [comment]
The reason why I'm trying to use both of them together is that, I have a dependency namely marked that reads markdown files & sources. The problem is that, it comes with ready css files with its dependency. In order to add dark support, I have to create yet another my own css files that should overwrite the out-of-box css files. In addition, my website uses tailwind for it's frontend visual part. However, I resolved this issue like that: 

https://github.com/00010023/wt.coursework2/blob/24e1f88be3ec308dc50f5d979848e97e0fd4c50b/client/components/Header.jsx#L29

**(P.S Please, don't judge too strictly my noobness 😰)**

**Comment by pacocoursey** [comment]
Your solution works, but it will cause a flicker (try refreshing the blog page) because you use `useEffect` to manage the styles.

I'm still not sure I understand why you need both. In your [markdown style](https://github.com/00010023/wt.coursework2/blob/main/client/styles/markdown.css) why don't you just use `.dark` here?

https://github.com/00010023/wt.coursework2/blob/24e1f88be3ec308dc50f5d979848e97e0fd4c50b/client/styles/markdown.css#L15
