### ISSUE TITLE
"Do not add <script> tags using next/head" message in development mode

### ISSUE THREAD

**Issue by musme** [pacocoursey/next-themes#84]
When next@12.0.11-canary.20 is used in development mode, there is a message in the console "Do not add <script> tags using next/head". So next@12.0.11 will also have this message.

Maybe use Script Component ( https://nextjs.org/docs/basic-features/script) instead of native script inside next/head.

**Comment by LordRonz** [comment]
can confirm, next@12.1.0 have this message

**Comment by pacocoursey** [comment]
Looking into this, thanks.

**Comment by pacocoursey** [comment]
Fixed, please upgrade to `next-themes@latest`!

**Comment by brokul-dev** [comment]
Hello @pacocoursey 
Thanks for your fix, it seems to be working now. Unfortunately, I have a problem with the new approach to the inline script.
Before your fix, I had the inline script hash included in my CSP:

![image](https://user-images.githubusercontent.com/78214221/154851732-fb230f63-bb22-41ec-ad47-8f9d4b54a4d4.png)

Now it seems to be impossible to include the hash in `script-src` because you're using `data:` to load the inline script:

![image](https://user-images.githubusercontent.com/78214221/154851766-732a725d-0f86-4643-a167-b0af2a942031.png)

I would rather not include `data:` in my CSP policy. Would it be possible not to load the script with `data:` and still use the inline one like before? Or could you suggest a "safe" workaround to whitelist your script?

**Comment by pacocoursey** [comment]
@brokul-dev The `nonce` prop is now supported, which you can use to allow-list the script. I'll add documentation for it soon 🙌

**Comment by brokul-dev** [comment]
@pacocoursey that's cool, but it would require generating a unique `nonce` on every page load with SSR. That's still quite an invasive solution because I use purely static generation.

**Comment by pacocoursey** [comment]
Oh, I totally misunderstood how that was supposed to be used.

Can you try `script-src 'data:'`? I'll start playing around with it locally as well to find a solution.

The ideal solution is to just fix how `next/script` works, it's a pretty bad API. That's the only reason I'm falling back to base64 encoding the script.

**Comment by brokul-dev** [comment]
Ye, I know, from my experience the `next/script` is really powerful from performance point of view, but it's also quite limited in some corner cases 😕

I've already checked and it works fine with CSP like `script-src 'self' data:`, but using `data:` is actually the same as `unsafe-inline`. I would rather avoid that. That would be great if you could find a walk around!

**Comment by brokul-dev** [comment]
By the way, is there any problem with using the inline script like below in your case? 
```tsx
<Script
    id='test'
    strategy='beforeInteractive'
>{`console.log("hello")`}</Script>
```

I'm asking because I saw [the comment in your code](https://github.com/pacocoursey/next-themes/blob/master/src/index.tsx#L246) saying that `next/script` doesn't accept the `children`. But I believe that it does 🙂

Reference: https://nextjs.org/docs/basic-features/script#inline-scripts

**Comment by pacocoursey** [comment]
Yes, `beforeInteractive` does not support inline script.

<img width="676" alt="CleanShot 2022-02-20 at 11 48 33@2x" src="https://user-images.githubusercontent.com/34928425/154853949-db4873cd-12c7-4f79-8306-157cb8773a50.png">

**Comment by brokul-dev** [comment]
Ok, I see now.

**Comment by pacocoursey** [comment]
The only thing I can think of is adding a unique prefix to the `next-themes` script, like encoding the comment `/* next-themes */` as the first part of the script, which gives it a stable prefix (`data:text/javascript;base64,LyogbmV4dC10aGVtZXMgKi8`).

Of course this doesn't prevent other inline scripts from copying the exact same prefix and bypassing the CSP header... so not a fix, but slightly improved.

**Comment by brokul-dev** [comment]
Perhaps it would be worth creating a ticket in the `next.js` repository (with a reference to this issue) so the next.js team knows that not supporting inline scripts with `beforeInterastive` strategy is problematic in this case?

**Comment by pacocoursey** [comment]
Opened: https://github.com/vercel/next.js/issues/34610

**Comment by pacocoursey** [comment]
Oh, it seems children is being passed. I'll try releasing a beta.

https://github.com/vercel/next.js/issues/34610#issuecomment-1046287034

**Comment by brokul-dev** [comment]
Hello @pacocoursey,
Any updates regarding this? I see that in the newest version of the library there is still a base64 encoded script.
