### ISSUE TITLE
Unable to access system theme on first load on v0.0.15

### ISSUE THREAD

**Issue by dsouzaajohn** [pacocoursey/next-themes#91]
Thanks for the wonderful package!

As per your [change logs](https://lifesaver.codes/answer/system-preference-doesn-t-work-by-default-20) for `v0.0.13-beta.1`, the default theme is immediately saved to `localStorage` on first load. 

However, I am currently experiencing an issue in `v0.0.15` where the default theme is not immediately saved to `localStorage` on first load, and only gets reflected when you switch themes.

**Comment by pacocoursey** [comment]
Hey, this was changed around 0.0.13 as you mentioned. Here's the comment describing the change: https://github.com/pacocoursey/next-themes/issues/20#issuecomment-784470942

> The default theme is **not immediately saved** to localStorage on first load, only when you switch theme

I think you misread – the theme is NOT immediately saved now. This is nice because you can change the `defaultTheme` for your site as needed, and unless users have manually changed the theme, they will be upgraded to the new default.
